language: java
dist: trusty
install: skip
sudo: required
services:
  - docker

jobs:
  include:

    - stage: build
      jdk: openjdk8
      script:
        - ./gradlew build -x buildNative -x testNative
    - stage: build
      jdk: oraclejdk9
      script:
        - ./gradlew build -x buildNative -x testNative
    - stage: build
      jdk: openjdk11
      script:
        - ./gradlew build -x buildNative -x testNative