democlient:
  client-id: demo-client
  redirect-uri: http://127.0.0.1:9095/client/callback
  pkce: false
  authorization:
    endpoint: http://auth-server:9000/oauth2/authorize
    response-type: code
    scope:
    - openid
    - profile
    - offline_access
  token:
    endpoint: http://auth-server:9000/oauth2/token
    client-secret: secret
  introspection:
    endpoint: http://auth-server:9000/oauth2/introspect
  userinfo:
    endpoint: http://auth-server:9000/userinfo


